spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/events
spring.datasource.username=postgres
spring.datasource.password=GAlo2bi2021
aws.region=us-east-2
aws.bucket.name=eventostec-imagens-daniboycam